source "https://supermarket.getchef.com"

metadata

# Examples
#cookbook "windows", "= 1.4.1"
#cookbook 'pvpnet', path: '/Users/reset/code/riot-cookbooks/pvpnet-cookbook'
#cookbook 'mysql', git: 'git://github.com/opscode-cookbooks/mysql.git'
#cookbook "artifact", github: "RiotGames/artifact-cookbook", tag: "0.9.8"
#cookbook 'itero-env-setup', "= 0.3.0", path: '../itero-env-setup'
